config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers do
    resources :tracks
  end
  root 'customers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
    has_many :tracks, dependent: :delete_all
    validates :short_name, :origin, :level, :full_name, :linkman, :email, presence: true
    REGULAR_EMAIL = /^([A-Za-z0-9_\-\.\u4e00-\u9fa5])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,8})$/
    validates :email,format:{with: REGULAR_EMAIL, :multiline => true }

    def latest_track_title
        if self.tracks.size > 0
            self.tracks[0].title
        else
          return "零记录"
        end
    end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :customer
  belongs_to :user, required: false
  default_scope -> { order(date: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :customers
  has_many :tracks, :through => :customers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [ :index, :show, :new ,:edit, :update, :destroy ]
  before_action :find_customer_and_check_permission, only: [ :show, :edit, :update, :destroy ]
  # GET /customers or /customers.json
  def index
      @my_customers = Customer.where(user_id: current_user.id)

  end

  # GET /customers/1 or /customers/1.json
  def show
    @customer = Customer.find(params[:id])
    @tracks = @customer.tracks
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.user_id = current_user.id
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "新建客户成功！" }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "更新客户信息成功！" }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:user_id, :short_name, :origin, :sq, :level, :full_name, :linkman, :address, :phone, :fax, :mobile, :email, :website, :main_purchase, :track_result, :note)
    end

    def find_customer_and_check_permission
      set_customer
      if current_user != @customer.user
        flash[:notice] = "没有权限，非管理员用户仅能查阅、编辑、修改自己的客户！"
        redirect_to root_path
      end
    end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, only:%i[ index show edit update destroy ]
  def index
    @customer = Customer.find(params[:customer_id])
    @tracks = Track.where(customer_id: @customer.id)

  end
  
  def new
    @customer = Customer.find(params[:customer_id])
    @track = Track.new
  end

  def edit
    @customer = Customer.find(params[:customer_id])
    @track = @customer.tracks.find(params[:id])
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @customer.user = current_user
    @track = Track.new(track_params)
    @track.customer = @customer

    if @track.save
      redirect_to customer_track_path(@customer,@track)
    else
      render :new
    end
  end

  def update
    @customer = Customer.find(params[:customer_id])
    @track = @customer.tracks.find(params[:id])
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to customer_track_path, notice: "更新客户信息成功！" }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @customer = Customer.find(params[:customer_id])
    @track = Track.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @track = @customer.tracks.find(params[:id])
    @track.destroy
    respond_to do |format|
      format.html { redirect_to customer_tracks_url, notice: "该条客户记录已经删除！" }
      format.json { head :no_content }
    end
  end

  private

  def track_params
    params.require(:track).permit(:title, :content, :date, :result)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
    def visit(website)
        if website =~ /^(?i)https?:\/\//
            link_to website
            else
                link_to website, "https://" + website.to_s, target:"_blank"
        end
    end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/common/_bread-split-nav.html.erb
    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <ol>
          <li><%= link_to '主页', root_path %></li>
          <li>客户 </li>
        </ol>
        <h2>List</h2>
        <p id="notice"><%= notice %></p>
      </div>


    </section><!-- End Breadcrumbs -->

app/views/common/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Yunjiu Info</h3>
            <p>
              中国 广东省 <br>
              东莞市 东城街道<br>
              万达广场 6栋406 <br><br>
              <strong>Phone:</strong> 13267445113<br>
              <strong>Email:</strong> y9info@163.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-lg-flex py-4">

      <div class="me-lg-auto text-center text-lg-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Yunjiu Info</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/Yunjiu Info-free-multipurpose-bootstrap-template/ -->
          <%# Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> %>
        </div>
      </div>
      <div class="social-links text-center text-lg-right pt-3 pt-lg-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

app/views/common/_header-nav.html.erb
  <!-- ======= Header navbar ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="index.html">Yunjiu Info</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto " href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li><a class="nav-link scrollto" href="#pricing">Pricing</a></li>
          <li><a class="active" href="blog.html">Blog</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><%= current_user ? link_to("退出登录", destroy_user_session_path, method: :delete, data: {confirm:"确认退出？"}, class:"nav-link scrollto") : link_to("登录", new_user_session_path, class:"nav-link scrollto")%>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header navbar -->

app/views/common/_top-header.html.erb
  <!-- ======= Top header ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:y9info@163.com">技术支持：y9info@163.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>132 6744 5113</span></i>
      </div>

      <div class="cta d-none d-md-flex align-items-center">
        <a href="#about" class="scrollto">Get Started</a>
      </div>
    </div>
  </section>

app/views/customers/edit.html.erb
<h1 class="text-center">编辑客户资料信息</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<div class="container-fluid">
<table class="table border border-success caption-top table-bordered">
  <caption>	你当前的位置：[主页]-[客户列表]</caption>
  <thead>
    <tr class="text-center">
      <th>序号</th>
      <th>客户简称</th>
      <th>来源</th>
      <th>SQ号码</th>
      <th>类别</th>
      <th>联系人</th>
      <th>邮箱</th>
      <th>最近跟进</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody class="text-center">
    <% i=0 %>
    <% @my_customers.each do |customer| %>
      <% i=i+1 %>
      <tr>
        <td><%= i %></td>
        <td><%= link_to customer.short_name,customer %></td>
        <td><%= customer.origin %></td>
        <td><%= customer.sq %></td>
        <td><%= customer.level %></td>
        <td><%= customer.linkman %></td>
        <td><a href="mailto:<%= customer.email %>" ><%= customer.email %></a></td>
        <%# 三元运算符 %>
        <td><%= customer.latest_track_title == "零记录"? (link_to "零",new_customer_track_path(customer)) :(link_to customer.latest_track_title, customer_tracks_path(customer),title:customer.tracks[0].content) %></td>  
        <td><%= image_tag("tab-images/del.gif")%><%= link_to '删除', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <div class="read-more">
      <%= link_to '新增客户', new_customer_path %>
    </div>
</div>

app/views/customers/new.html.erb
 <div class="container">
   <div class="col-lg-8">
     <h1>新增客户：</h1>
    </div>
</div>
<%= render 'form', customer: @customer %>


 <%= link_to '返回', customers_path%>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

				<div class="container">
					<div class="main-body">
						<div class="row">
							<div class="col-lg-4">
								<div class="card">
									<div class="card-body">
										<div class="d-flex flex-column align-items-center text-center">
											<%= image_tag("avatar-2.png",alt:"Admin",class:"rounded-circle p-1 bg-primary",width:"110") %>
											<div class="mt-3">
												<h4><%= @customer.linkman %></h4>
												<p class="text-secondary mb-1"><%= @customer.full_name %></p>
												<p class="text-muted font-size-sm"><%= @customer.address %></p>
												<%= link_to("跟进记录", customer_tracks_path(@customer), class: "btn btn-primary")%>
												<button class="btn btn-outline-primary"><a href="mailto:<%= @customer.email %>" >给客户发邮件</a></button>
												
											</div>
										</div>
										<hr class="my-4" />
										<ul class="list-group list-group-flush">
											<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
												<h6 class="mb-0">网址：</h6>
												<span class="text-secondary ">
												<%= visit @customer.website %>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
												<h6 class="mb-0">简称：</h6>
												<span class="text-secondary"><%= @customer.short_name %></span>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
												<h6 class="mb-0">来源：</h6>
												<span class="text-secondary"><%= @customer.origin %></span>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
												<h6 class="mb-0">SQ号码：</h6>
												<span class="text-secondary">  <%= @customer.sq %></span>
											</li>
											<li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
												<h6 class="mb-0">等级</h6>
												<span class="text-secondary"><%= @customer.level %></span>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-lg-8">
								<div class="card">
									<div class="card-body">
									<%= form_for [@customer] do |form| %>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">Email</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%= form.text_field :email, class: "form-control" %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">Phone</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%= form.text_field :phone, class: "form-control" %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">Mobile</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%= form.text_field :phone, class: "form-control" %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">Fax</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%= form.text_field :fax, class: "form-control" %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">客户关注产品</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%=  form.text_area :main_purchase, class: "form-control"  %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">跟踪结果</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%=  form.text_area :track_result, class: "form-control"  %>
											</div>
										</div>
										<div class="row mb-3">
											<div class="col-sm-3">
												<h6 class="mb-0">备注</h6>
											</div>
											<div class="col-sm-9 text-secondary">
												<%=  form.text_area :note, class: "form-control",cols:"40", rows:"5", style:"height:130px" %>
											</div>
										</div>

										<div class="row">
											<div class="col-sm-3"></div>
											<div class="col-sm-9 text-secondary">
												<%= form.submit "Save Changes",class: "btn btn-primary px-4 " %>
											</div>
										</div>
									</div>
									
									<% end %>

								</div>
							
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-cmn-Hans">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="description" content="CRM">
  <meta name="author" content="Yunjiu Info">
  <%# <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal"> %>
  <%= favicon_link_tag image_path("favicon.ico") %>
  <title>Rails102</title>
</head>

<body>
    <%= render "common/top-header" %> 
    <%= render "common/header-nav" %> 
    <%= render "common/bread-split-nav" %> 

  <main id="main">



    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-12 entries">

            <article class="entry">

              <%# <div class="entry-img">
                <img src="assets/img/blog/blog-1.jpg" alt="" class="img-fluid">
              </div> %>

              <%# <h2 class="entry-title">
                <a href="blog-single.html">客户列表</a>
              </h2> %>

            <div class="entry-meta">
              <ul>
               <% if current_user %>
                    <li><%= link_to" 点此查阅您的全部#{current_user.customers.size}个客户",customers_path %></li> 
                <% end %> 
                <li><%= current_user ? "当前销售人员：#{current_user.email}" : "您尚未登录系统" %></li>
                <li ><time datetime="<%= Date.today %>"><%= Date.today %></time></li>
              </ul>
            </div>
              <div class="entry-content">
                <%= yield %>
              </div>

            </article><!-- End blog entry -->

           
            <div class="blog-pagination">
              <ul class="justify-content-center">
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
              </ul>
            </div>

          <%# </div><!-- End blog entries list -->

          <%= render "common/sidebar" %>

        <%# </div> %> 

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  <%= render "common/footer" %>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


</body>

</html>

app/views/tracks/_form.html.erb
<%= form_for [@customer,@track] do |form| %>
    <% if @track.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>
        <ul>
        <% @track.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <div class="blog-author align-items-center">
        <div class="reply-form">
            <h4>客户跟踪记录</h4>
            <p>客户跟踪记录情况仅本人和管理员权限可以查阅 * </p>
        
            <div class="row">
                <div class="col-6  mb-3">
                    <%= form.label :记录标题 %>
                    <%= form.text_field :title, class:"form-control",placeholder:"输入标题*" %>
                </div>

                <div class="col-6  mb-3">
                    <%= form.label :跟进日期 %>
                    <%= form.date_field :date, class:"form-control" %>
                </div>
            </div>
            
            <div class="row">
                <div class="mb-3">
                    <%= form.label :跟进内容 %>
                    <%= form.text_area :content, class:"form-control", rows:"5", placeholder:"输入本次跟进客户的主要内容及交流情况*" %>
                </div>
            </div>

            <div class="row">
                <div class="mb-3">
                    <%= form.label :反馈及结果 %>
                    <%= form.text_area :result, class:"form-control", rows:"5", placeholder:"客户反馈及跟进结果情况*" %>
                </div>
            </div>
            
            <%= form.submit "提交",class: "btn btn-primary col-12 " %>
        </div>
    </div>
<% end %>

app/views/tracks/edit.html.erb
<h2 class="text-center">记录修订 | <%= @customer.short_name %></h2>
<%= render 'form' %>

app/views/tracks/index.html.erb
<div class="blog-author d-flex align-items-center">
    <%= image_tag("avatar-2.png", class:"rounded-circle float-left") %>

    <div>
        <h4><%= @customer.linkman %></h4>
        <div class="row">
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item "><%= @customer.full_name %></li>
                <li class="list-group-item ">采购：<%= @customer.main_purchase %></li>
                <li class="list-group-item ">SQ号：<%= @customer.sq %></li>
            </ul>
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item ">电话：<%= @customer.phone %></li>
                <li class="list-group-item ">邮箱：<%= @customer.email %></li>
                <li class="list-group-item ">手机：<%= @customer.mobile %></li>
            </ul>
            <p><%= @customer.address %></p>
            <div class="read-more">
                <%= link_to '新增客户跟踪记录', new_customer_track_path %>
            </div>
        </div>
    </div>
</div>


    <h4>客户跟踪:</h4>
    <p>共<%= @customer.tracks.size %>次客户跟踪记录 <small>-<%= @customer.full_name %></small></p>
    <li <hr class="dropdown-divider"></li>
    <% @tracks.each do |track| %>
        <div class="blog-comments">             
                <div class="comment">
                 <%= link_to image_tag("tab-images/del.gif",class:"float-end"),customer_track_path(@customer,track),method: :delete,date:{confirm:"确认删除？"} %>
                    <div class="d-flex">
                        <div class="comment-img"><%= image_tag("comments-3.jpg")%></div> 
                        <div>
                            <h5><a href="<%= edit_customer_track_path(@customer,track) %>"><%= image_tag("tab-images/edt.gif") %><%= track.title %></a></h5>
                            <time><%= track.date %></time>
                            <div class="mb-3">
                                跟进内容：<%= track.content %>
                            </div>
                            <p>
                                跟进结果：<%= track.result %>
                            </p>
                        </div>
                    </div>
                </div>
        </div>

    <% end %>

app/views/tracks/new.html.erb
<div class="blog-author d-flex align-items-center">
    <%= image_tag("avatar-2.png", class:"rounded-circle float-left") %>
    <div>
        <h4><%= @customer.linkman %></h4>
        <div class="row">
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item "><%= @customer.full_name %></li>
                <li class="list-group-item ">采购：<%= @customer.main_purchase %></li>
                <li class="list-group-item ">SQ号：<%= @customer.sq %></li>
            </ul>
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item ">电话：<%= @customer.phone %></li>
                <li class="list-group-item ">邮箱：<%= @customer.email %></li>
                <li class="list-group-item ">手机：<%= @customer.mobile %></li>
            </ul>
            <p><%= @customer.address %></p>
        </div>
    </div>
</div>

<%= render 'form' %>


 <%= link_to '返回', customers_path %>

app/views/tracks/show.html.erb
<div class="blog-author d-flex align-items-center">
    <%= image_tag("avatar-2.png", class:"rounded-circle float-left") %>
    <div>
        <h4><%= @track.customer.linkman %></h4>
        <div class="row">
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item "><%= @track.customer.full_name %></li>
                <li class="list-group-item ">采购：<%= @track.customer.main_purchase %></li>
                <li class="list-group-item ">SQ号：<%= @track.customer.sq %></li>
            </ul>
            <ul class="list-group list-group-flush col-6">
                <li class="list-group-item ">电话：<%= @track.customer.phone %></li>
                <li class="list-group-item ">邮箱：<%= @track.customer.email %></li>
                <li class="list-group-item ">手机：<%= @track.customer.mobile %></li>
            </ul>
            <p><%= @customer.address %></p>
        </div>
    </div>
</div>


<div class="blog-comments">
        <div class="entry-meta ">
            <%= link_to"点此查阅该客户全部#{@customer.tracks.size }条跟踪记录", customer_tracks_path %>
        </div> 
       <div class="comment">
        <div class="d-flex">
            <div class="comment-img"><%= image_tag("comments-3.jpg")%></div>
            <div>
            <h5><a href="<%= edit_customer_track_path %>"><%= image_tag("tab-images/edt.gif")%><%= @track.title %></a> </h5>
            <time><%= @track.date %></time>
            <div class="mb-3">
                跟进内容：<%= @track.content %>
            </div>
            <p>
                跟进结果：<%= @track.result %>
            </p></div>
        </div>
    </div>
</div>
    <div class="read-more">
      <%= link_to '增加新记录', new_customer_track_path %>
    </div>